### ISSUE TITLE
Missing 0–extern subpass dependency in HelloTriangle

### ISSUE THREAD

**Issue by krOoze** [FacticiusVir/SharpVk#19]
HelloTriangle(UWP) is missing "output"(0–extern) subpass dependency making swapchain image "available" for the presentation.

**Comment by FacticiusVir** [comment]
Is this referring to https://github.com/FacticiusVir/SharpVk/blob/UWP/SharpVk/SharpVk.HelloTriangle.Uwp/MainPage.xaml.cs#L347 or have I misunderstood?

**Comment by krOoze** [comment]
^ yes that. It has external&ndash;0 dependency, but no 0&ndash;external.

**Comment by krOoze** [comment]
@FacticiusVir You seem to have src and dst parameters swap in the added dependency.

**Comment by FacticiusVir** [comment]
For the stage masks?

**Comment by krOoze** [comment]
Both stage and access mask

**Comment by FacticiusVir** [comment]
Fair does, I still need to read up on subpass dependencies; thanks for the catch!
