### ISSUE TITLE
Generator Syntax Error

### ISSUE THREAD

**Issue by sunkin351** [FacticiusVir/SharpVk#26]
Files:
LayerProperties.cs
PhysicalDeviceProperties.cs

screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/9635201/20415131/a6b709d8-acf3-11e6-9f11-cff6dd414924.png)

~~Have it remove the `uint` to `int` conversion, its really not needed anyway.~~
Edit:
It does need it, sorry, but it isnt accepting the conversion either because the conversion would make it "non-constant".

**Comment by FacticiusVir** [comment]
Interesting; this is using the Mono compiler? Will look at changing the Size constants to regular ints for cross-compatibility.

**Comment by sunkin351** [comment]
That fixed it.
Before I close this, (This is off-topic, I am sorry, I have not found a good solution to this yet.) how would you recommend going about getting an XCB window handle (connection and window index) for linux with this? I have tried to get it with unmanaged code but there have been many issues.

**Comment by FacticiusVir** [comment]
I'm not hugely familiar with .NET on Linux, I'm afraid, but I was looking at moving the sample code to something like GLFW to make them cross-platform; I'll have a look this weekend and see what I can get working.

**Comment by sunkin351** [comment]
That would be awesome, please do. :)
