### ISSUE TITLE
PCL support

### ISSUE THREAD

**Issue by amerkoleci** [FacticiusVir/SharpVk#28]
Hi, is possible to add support for Portable class library support, similar to Mono VulkanSharp, otherwise I wont be able to compile it under Android.

**Comment by FacticiusVir** [comment]
Sure, will sort a project definition this evening.

**Comment by FacticiusVir** [comment]
Looks like I need some more target definitions installed on my laptop to test this properly, and as I'm in a cottage by Loch Ness at the moment I don't quite have the bandwidth to download them :-D Will get back to it over the weekend - did you need the NuGet package updating, or just the repo?

**Comment by amerkoleci** [comment]
Don't worry take your time, I dont need any version soon :)

**Comment by FacticiusVir** [comment]
The main SharpVk library is now a PCL which should have the right target platforms for Xamarin. Let me know if it works for you!

**Comment by FacticiusVir** [comment]
The core libraries are currently being rewritten for Standard, either 1.4 or 1.6.

**Comment by FacticiusVir** [comment]
The .Net Standard 2.0 release is now published, including cross-platform support for Mono & Android.
