### ISSUE TITLE
Next field not set to  0

### ISSUE THREAD

**Issue by jcoder58** [FacticiusVir/SharpVk#30]
I got the following warning from Vulkan:

>ParameterValidation: vkCreateGraphicsPipelines: value of pCreateInfos[0].pStages[1].pNext must be NULL.  This warning is based on the Valid Usage documentation for version 30 of the Vulkan header.  It is possible that you are using a struct from a private extension or an extension that was added to a later version of the Vulkan header, in which case your use of pCreateInfos[0].pStages[1].pNext is perfectly valid but is not guaranteed to work correctly with validation enabled

Looking through your code, I saw that you did not explicitly set the Next field when you marshaled the structures.   I fixed the warning by adding 

        pointer->Next = null;

to PipelineShaderStageCreateInfo.MarshalTo to fix the issue I was having.

**Comment by FacticiusVir** [comment]
Looks like fall-out from the marshalling rework done for Linux/Xamarin - struct memory was originally zeroed when allocated, but that was swapped for explicitly initialising all fields. Guess like I missed some! Will update the generator to fix.

**Comment by FacticiusVir** [comment]
Huh, actually subtler than that; memory zeroing still happens for individual struct allocates, but not for arrays. Either way, the fix is the same, let me know if that resolves your validate error.

**Comment by jcoder58** [comment]
That fixed it.
