### ISSUE TITLE
Vertex buffer and uniform buffer crashing

### ISSUE THREAD

**Issue by greenmughal** [FacticiusVir/SharpVk#36]
Without any exception? On 2nd frame... how to increase error detection?

**Comment by realvictorprm** [comment]
Can you provide more information?
I'm sure you already enabled all validation layers of Vulkan?

**Comment by greenmughal** [comment]
How to enable all validation layers in these 2 examples?

**Comment by realvictorprm** [comment]
which examples?

**Comment by greenmughal** [comment]
Uniform buffer sample and index buffer sample

**Comment by FacticiusVir** [comment]
Hey! Thanks for trying the samples. Can I ask what OS, framework (e.g. .NET 4.6, Mono, et cetera) and what graphics card(s) you're running on?

Both of those samples have standard validation checks enabled, so any additional errors should be logged to Debug output - you can modify [this](https://github.com/FacticiusVir/SharpVk-Samples/blob/master/SharpVk.UniformBuffers/Program.cs#L361) line if you want to output to other logging. You can also modify the list of [debug flags](https://github.com/FacticiusVir/SharpVk-Samples/blob/master/SharpVk.UniformBuffers/Program.cs#L352) to include information or debug, which should help isolate the line that's crashing.

**Comment by greenmughal** [comment]
>>Failed to find vkGetDeviceProcAddr in layer nvoglv32.dll
Is this line responsible?
[InfoLog-PasteBin](https://pastebin.com/gdaas7rz)

My Card is Nvidia 920M Laptop graphics card. I can run above 90% Vulkan C++ Samples.

**Comment by FacticiusVir** [comment]
I've seen some problems occur with nvoglv32.dll and older versions of the Vulkan SDK - do you have the latest  SDK (1.0.54.0) installed?

**Comment by greenmughal** [comment]
Wait let me try updating all nvidia, vulkan sdk and drivers...

**Comment by greenmughal** [comment]
Thanks for your feedback, it was drivers...

**Comment by FacticiusVir** [comment]
No worries, glad that fixed it! Will also look at adding some more pro-active version & DLL checks in the instance/device start-up, to give more helpful feedback.
