### ISSUE TITLE
`layerName` isn't optional

### ISSUE THREAD

**Issue by Y-Less** [FacticiusVir/SharpVk#51]
`Instance.EnumerateExtensionProperties` and `PhysicalDevice.EnumerateDeviceExtensionProperties` take an optional `pLayerName`, but there's no default `null` on the parameter:

```cs
        public unsafe SharpVk.ExtensionProperties[] EnumerateDeviceExtensionProperties(string layerName)
```

**Comment by FacticiusVir** [comment]
In the `.partial` files that's a manual change I can make directly; I know there's also a few cases in the generator that don't detect optional inputs so I'll check this for the generated code.
