### ISSUE TITLE
No layers reported when run outside of console.

### ISSUE THREAD

**Issue by Loen10** [FacticiusVir/SharpVk#56]
When running my application by simply double clicking the executable, it crashes as no layers are reported via Instance.EnumerateLayerProperties. 

I'm fairly certain this is because when it is run without a console, the application does not have access to my enviornment variables that I have set up for Vulkan. But I don't know how I could fix this.

INFO:
OS: Linux Mint 19.2
SharpVk Nuget Version: 0.4.2
.NET Core Version: 3.0

**Comment by FacticiusVir** [comment]
Interesting - to confirm, if you run a console application and call Instance.EnumerateLayerProperties, do you get the current list of arrays?

**Comment by WildTheOne** [comment]
Yes, it reports all the layers when run from a console, both by doing "dotnet run", and "./executable".

**Comment by WildTheOne** [comment]
Also, is it normal to have to install the VulkanSDK along with SharpVk, if so what should I do to properly link the two?

**Comment by FacticiusVir** [comment]
The Vulkan SDK is not necessary, but it does provide validation layers & debugging information so I'd highly recommend it. There's no explicit linking required to use those layers from SharpVk.

I'm using working on Windows, but I'll set up a test rig and see if I can replicate your issue.

**Comment by WildTheOne** [comment]
Ok so I tested the issue with a C++ executable using the Vulkan SDK and it did the same thing.

So the problem is not unique to SharpVk.

My solution was to run the executable from a script file that sets the enviornment variables before running the executable.
Or I could set them from within the runtime code itself.
