### ISSUE TITLE
Expose internal methods / Low-level wrapper?

### ISSUE THREAD

**Issue by FaberSanZ** [FacticiusVir/SharpVk#57]
Hi,

Open form to have a version of the unmanaged library.

**Comment by FacticiusVir** [comment]
The [SharpVk.Interop](https://github.com/FacticiusVir/SharpVk/tree/master/src/SharpVk/Interop) namespace gives you direct access to the low-level, unsafe types and delegates. You can use the `NativeLibrary` and `CommandCache` classes to load functions. The only types that are typically `internal` are the utility classes used by SharpVk itself.

**Comment by FaberSanZ** [comment]
Thank you, I look forward to a version of SDK 1.1.130 and Nuget Updated
