### ISSUE TITLE
Replace T4 Templates

### ISSUE THREAD

**Issue by FacticiusVir** [FacticiusVir/SharpVk#8]

**Comment by discosultan** [comment]
Just out of curiosity, why T4 templates aren't sufficient and what are they going to be replaced with?

**Comment by FacticiusVir** [comment]
There's a couple of issues with T4 templates - they have limited portability as the T4 processor is part of Visual Studio so they're not usable (to my knowledge) on Linux without additional tools, and I've noticed they render differently on different machines (lots of extra newlines appear sometimes, though that's possibly a side-effect of Git's Windows-to-Unix newline conversion). They're also clumsy when building complex single-line output, like the parameter set of a method, can't reference external code without it being pre-built (hence having SharpVk.VkXml output to a separate bin folder) and cause file locks if you debug them in Visual Studio.
All round it's not _necessary_ to replace them, but they have lots of little problems and I suspect it's going to make life easier as I look at more complex transforms for the public API; I'm working on the prototype generators in SharpVk.Generator, and the final version is very likely to be an MVVM-esque console app built on top of the TypeSet model in SharpVk.VkXml.
